fixtures:
  repositories:
    chocolatey:
      repo: 'https://github.com/chocolatey/puppet-chocolatey.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.13.0'
  symlinks:
    nxlog: "#{source_dir}"
